### ISSUE TITLE
Cannot Find Module

### ISSUE THREAD

**Issue by ArtieFuzzz** [m-Phoenix852/sxcu.js#1]
Running in a docker container.
Edit: My discord if you need to contact me: ArtieFuzzz#8298

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module './ogproperties'
Require stack:
- /home/container/node_modules/sxcu.js/src/Image/ImageMeta.js
- /home/container/node_modules/sxcu.js/src/Collection/CollectionMeta.js
- /home/container/node_modules/sxcu.js/src/Collection.js
- /home/container/node_modules/sxcu.js/src/Image.js
- /home/container/node_modules/sxcu.js/src/index.js
- /home/container/src/Commands/Miscellaneous/paste.js
- /home/container/node_modules/discord-akairo/src/struct/AkairoHandler.js
- /home/container/node_modules/discord-akairo/src/index.js
- /home/container/src/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/sxcu.js/src/Image/ImageMeta.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/container/node_modules/sxcu.js/src/Collection/CollectionMeta.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/container/node_modules/sxcu.js/src/Image/ImageMeta.js',
    '/home/container/node_modules/sxcu.js/src/Collection/CollectionMeta.js',
    '/home/container/node_modules/sxcu.js/src/Collection.js',
    '/home/container/node_modules/sxcu.js/src/Image.js',
    '/home/container/node_modules/sxcu.js/src/index.js',
    '/home/container/src/Commands/Miscellaneous/paste.js',
    '/home/container/node_modules/discord-akairo/src/struct/AkairoHandler.js',
    '/home/container/node_modules/discord-akairo/src/index.js',
    '/home/container/src/main.js'
  ]
}

**Comment by m-Phoenix852** [comment]
> Running in a docker container.
> Edit: My discord if you need to contact me: ArtieFuzzz#8298
> 
> internal/modules/cjs/loader.js:834
> throw err;
> ^
> 
> Error: Cannot find module './ogproperties'
> Require stack:
> 
> * /home/container/node_modules/sxcu.js/src/Image/ImageMeta.js
> * /home/container/node_modules/sxcu.js/src/Collection/CollectionMeta.js
> * /home/container/node_modules/sxcu.js/src/Collection.js
> * /home/container/node_modules/sxcu.js/src/Image.js
> * /home/container/node_modules/sxcu.js/src/index.js
> * /home/container/src/Commands/Miscellaneous/paste.js
> * /home/container/node_modules/discord-akairo/src/struct/AkairoHandler.js
> * /home/container/node_modules/discord-akairo/src/index.js
> * /home/container/src/main.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:687:27)
>   at Module.require (internal/modules/cjs/loader.js:903:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/container/node_modules/sxcu.js/src/Image/ImageMeta.js:4:22)
>   at Module._compile (internal/modules/cjs/loader.js:1015:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>   at Module.load (internal/modules/cjs/loader.js:879:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>   at Module.require (internal/modules/cjs/loader.js:903:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/container/node_modules/sxcu.js/src/Collection/CollectionMeta.js:1:19)
>   at Module._compile (internal/modules/cjs/loader.js:1015:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>   at Module.load (internal/modules/cjs/loader.js:879:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/container/node_modules/sxcu.js/src/Image/ImageMeta.js',
>   '/home/container/node_modules/sxcu.js/src/Collection/CollectionMeta.js',
>   '/home/container/node_modules/sxcu.js/src/Collection.js',
>   '/home/container/node_modules/sxcu.js/src/Image.js',
>   '/home/container/node_modules/sxcu.js/src/index.js',
>   '/home/container/src/Commands/Miscellaneous/paste.js',
>   '/home/container/node_modules/discord-akairo/src/struct/AkairoHandler.js',
>   '/home/container/node_modules/discord-akairo/src/index.js',
>   '/home/container/src/main.js'
>   ]
>   }

It should be fixed by the 1.0.1 update. Update sxcu.js, and try.

**Comment by ArtieFuzzz** [comment]
It works! Thanks for fixing it
